# Theme: lock-wood
# By: Jakub Gawlik | info@caasi.dev
# Url: https://github.com/lock-wood
# A calm, muted dark colour scheme for Neovim, terminals, and the web.

# Basic colours
foreground #b6b2c6
background #1a1c20
cursor #b6b2c6
cursor_text_color #1a1c20
selection_background #242832
selection_foreground #b6b2c6

# ANSI colours
color0 #4e505b
color1 #c08281
color2 #759c75
color3 #aa9980
color4 #254a65
color5 #ae85ab
color6 #699b98
color7 #b6b2c6

# Bright colours
color8 #504c5e
color9 #b48787
color10 #699f68
color11 #9b9361
color12 #587b98
color13 #af98c1
color14 #6b9b97
color15 #b7b2c1

# Optional: URL colour, marks, etc.
url_color #6b9b97
mark1_foreground #1a1c20
mark1_background #ae85ab
